version: "3"
services:
  nosql-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/users/node_modules

  comments:
    build:
      dockerfile: Dockerfile
      context: ./comments
    container_name: comments
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/comments/node_modules

  posts:
    build:
      dockerfile: Dockerfile
      context: ./posts
    container_name: posts
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app/
      - /app/posts/node_modules


  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - comments
      - posts
    ports:
      - 80:80
